# Generated by Django 6.1.1 on 2026-09-30 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(blank=True, max_length=120)),
                ('target_role', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(choices=[('Student', 'Student'), ('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior')], default='Junior', max_length=20)),
                ('preferred_interview_type', models.CharField(choices=[('Technical', 'Technical'), ('Behavioral', 'Behavioral'), ('HR', 'HR'), ('Mixed', 'Mixed')], default='Technical', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
