# Generated by Django 6.1.1 on 2026-09-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='field_of_study',
            field=models.CharField(blank=True, default='Computer Science', max_length=120),
        ),
    ]
