# Generated by Django 6.0.6 on 2026-10-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountprofile_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='target_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
